---
title: "ARIMA - Ristorante1"
output:
  prettydoc::html_pretty:
    df_print: paged
    highlight: vignette
    theme: architect
    toc: yes
    toc_depth: 5
  beamer_presentation:
    colortheme: lily
    fig_caption: no
    fig_height: 6
    fig_width: 7
    fonttheme: structurebold
    theme: Hannover
    toc: yes
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '5'
  pdf_document:
    toc: yes
    toc_depth: 5
  slidy_presentation:
    highlight: default
  ioslides_presentation:
    css:
    - css/fonts.css
    - css/custom.css
    - css/title-slide.css
    - css/slide-background.css
    includes:
      before_body: html/TimeSeriesAnalysis.html
    toc: yes
    transition: default
    widescreen: yes
course: Progetto Data Science Lab
---

```{r}
# Clean Workspace
rm(list=ls())
```

```{r setup, include=FALSE}
# Use 'verbatim = TRUE' as chunk option to show chunk code as is
require(knitr)
hook_source_def = knit_hooks$get('source')
knit_hooks$set(source = function(x, options){
  if (!is.null(options$verbatim) && options$verbatim){
    opts = gsub(",\\s*verbatim\\s*=\\s*TRUE\\s*", "", options$params.src)
    bef = sprintf('\n\n    ```{r %s}\n', opts, "\n")
    stringr::str_c(bef, paste(knitr:::indent_block(x, "    "), collapse = '\n'), "\n    ```\n")
  } else {
     hook_source_def(x, options)
  }
})
```

# Setting & Function

```{r include=FALSE}
set.seed(100)

# Setting librerie utili
# Package names
packages <- c("readxl",  "readr", "forecast", "dplyr", "ggplot2",
              "lubridate", "KFAS", "tseries", "xts", "fastDummies") 

# Install packages if not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# Packages loading
invisible(lapply(packages, library, character.only = TRUE))


# MAPE 
mape <- function(actual,pred){
  mape <- mean(abs((actual - pred)/actual))*100
  return (mape)
}

#MSE
rmse <- function(actual, pred){
  rmse <- sqrt(mean((actual - pred)^2))
  return (rmse)
}

# Significatività dei parametri
pars_test <- function(coef, var_coef){
  test <- (1-pnorm(abs(coef)/sqrt(diag(var_coef))))*2
  return(test)
}

# Grafico errore percentuale 
err_plot <- function(actual, pred){
  require(xts)
  err_perc <- ((actual - xts(pred, order.by = index(actual)))/(xts(actual, order.by = index(actual))))*100
  return(plot(err_perc, ylab="% errore", main="Errore percentuale di previsione"))

}

```

## Load Data & Manipulation


Periodo considerato: dal **07/05/2020** (giorno di riapertura post 1° lockdown)

```{r}
df <- read.csv("..\\Dati ristoranti\\post-covid_r1.csv")
head(df)
```

Considero solo le variabili d'interesse

```{r}
df$data  <- parse_date(df$data, "%Y-%m-%d", locale = locale("it"))
df <- subset(df,
             select = c("data", "lordototale", "Season", "Giorno","Weekend", "Festivo", "Pioggia", "ColoreCOVID", "Dose1", "Dose2", "DoseUnica", "Booster1", "Booster3Dosi", "Booster2", "BENZINA.LITRO", "GASOLIO_AUTO.LITRO", "GPL.LITRO","GASOLIO_RISCALDAMENTO.LITRO"))

```


```{r}
# Controllo che non ci siano na
xreg[is.na(xreg)==TRUE,] # Non ci sono Nan
```

```{r}
# Creo dataframe contenente le sole variabili esplicative
xreg<- df[,-2]
```

```{r}
xreg$Pioggia[xreg$Pioggia ==""] <- "False" 
xreg$ColoreCOVID[xreg$ColoreCOVID==""] <- "NoColore"
xreg$Dose1[is.na(xreg$Dose1)] <- 0
xreg$Dose2[is.na(xreg$Dose2)] <- 0
xreg$DoseUnica[is.na(xreg$DoseUnica)] <- 0
xreg$Booster1[is.na(xreg$Booster1)] <- 0
xreg$Booster2[is.na(xreg$Booster2)] <- 0
xreg$Booster3Dosi[is.na(xreg$Booster3Dosi)] <- 0
```



```{r}
vendite_r1 <- df[,2]
vendite_r1[is.na(vendite_r1)] # Non ci sono NaN
vendite_r1[vendite_r1 == 0] # 9 valori a zero, probabilmente chiusure oppure mancanza di registrazioni degli incassi 
```

```{r}
vendite_r1 <- msts(vendite_r1, seasonal.periods=c(7,365.25), ts.frequency = 7)
plot(vendite_r1)
```

```{r}
vendite_r1_dec <- mstl(vendite_r1) 

autoplot(vendite_r1_dec)
```

## Salvataggio errori


```{r}
matrices <- list(e1 = e1, e1_percentage = e1_percentage, e1_estimate = e1_estimate, e1_groundtruth = e1_groundtruth, e3 = e3, e3_percentage = e3_percentage, e3_estimate = e3_estimate, e3_groundtruth = e3_groundtruth, e2 = e2, e2_percentage = e2_percentage, e2_estimate = e2_estimate, e2_groundtruth = e2_groundtruth)

for (i in 1:length(matrices)) {
  # Aggiungo la colonna date
  df_temp <- xts(matrices[[i]], as.Date(as.character(df$data), format = "%Y-%m-%d"))
  write.csv(data.frame(date=index(df_temp), coredata(df_temp)),
            paste0("./Errors/ARIMA/ARIMA_Covid_", names(matrices)[i], ".csv"))
}

```
